### ISSUE TITLE
Implement access token refreshing

### ISSUE THREAD

**Issue by matir91** [IDme/ID.me-WebVerify-SDK-Android#9]
The SDK should handle the refreshing of the access token without external input.

The access token refreshing can happen in different ways and depends on the endpoints provided by the backend.

At first the options would be:
* The server sends a new token with every response thus refreshing the token with every request.
* The SDK periodically refreshes the access token (certain time before it expires)
* The SDK lets the access token expire and refreshes it for the first request after its expiration time.

we should discuss it in the [iOS issue](https://github.com/IDme/ID.me-WebVerify-SDK-iOS/issues/7)

**Comment by matir91** [comment]
Implementation changes to support refresh token feature

`IDmeWebVerify` class will be a singleton class. It’ll manage the access token and refresh token logic. Both tokens will be associated with one scope. It mean that one user can be associated with only one scope. Is it right?

`IDmeWebVerify` will have 5 public methods:
* `initialize(Context context, String clientID, String redirectURI)`
* `login(Activity activity, Scope scope, callback)`
* `getAccessToken(Scope scope, callback)`
* `getAccessToken(Scope scope, Boolean force, callback)`
* `getUserProfile(callback)`
* `logOut(callback)`

`public static void initialise(Context context, String clientID, String redirectURI)`
This method should be called only one time from the Application class's onCreate method and before making any request to the SDK API. 
This method will initialize all the common variables. In a future version it might throw a background process which will refresh the token automatically before it’s expiration. 


`login(Activity activity, Scope scope)`
This method will have the same logic as the current ` StartWebView()` method. It will throw the login process and returns the access token in the callback. The callbacks are a way of return information in an async task. These callbacks are defined as an interface which has 2 basic methods, `onSuccess` and `onError`


`getAccessToken` 
This method will get the actual access token. The `force` boolean means that the token will be refreshed


`getUserProfile`
This method will get the user profile


`logOut` 
This method will delete all session information

**Comment by bryant1410** [comment]
Sounds good. Just a minor comment: "forceReload" instead of "force" seems clearer to know what it does.

**Comment by matir91** [comment]
#25
